# Example labeler configuration
# Add your label rules here. See https://github.com/actions/labeler for syntax.

# Example:
docs:
  - '**/*.md'
tests:
  - '**/test_*.py'
provider:
  - 'private_gpt/Provider/**'
cli:
  - 'private_gpt/cli.py'
